license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/joe-vettek/Dynamic-Trees-for-Beachparty"

[[mods]]
modId="dtbeachparty"
version="${file.jarVersion}"
displayName="Dynamic Trees for Beachparty"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-for-beachparty"
logoFile="logo.png"
credits=""
authors="joe_vettek(jianzoushihu)"
description='''
Adds Dynamic Trees compatibility for Beachparty.
'''

[[dependencies.dtbeachparty]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbeachparty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbeachparty]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.4.8,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbeachparty]]
    modId="dtaddon_lib"
    mandatory=true
    versionRange="[0.1.0-BETA2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbeachparty]]
    modId="beachparty"
    mandatory=true
    versionRange="[2.0.3,)"
    ordering="AFTER"
    side="BOTH"
